import React, { createContext, useContext, useState } from 'react';

type Language = 'pt' | 'en' | 'es';

interface LanguageContextType {
  language: Language | null;
  setLanguage: (lang: Language | null) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    welcome_back: 'Bem-vindo de volta',
    this_weeks_agenda: 'Agenda da Semana',
    dashboard: 'Painel',
    agenda: 'Agenda',
    clinics: 'Clínicas',
    profile: 'Perfil',
    logout: 'Sair',
    install_app: 'Instalar App',
    save: 'Salvar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Excluir',
    add_pet: 'Adicionar Pet',
    edit_pet: 'Editar Pet',
    everything_up_to_date: 'Tudo em dia',
    pending_care: '1 cuidado pendente',
    overdue_vaccines: 'Vacinas atrasadas',
    view_full_profile: 'Ver ficha completa',
    weight: 'Peso',
    birthday: 'Aniversário',
    health_nutrition: 'Saúde & Nutrição',
    basic_identity: 'Identidade Básica',
    pet_name: 'Nome do Pet',
    breed: 'Raça',
    birth_date: 'Data de Nascimento',
    food_type: 'Alimentação',
    allergies: 'Alergias',
    health_conditions: 'Condições de Saúde',
    medication: 'Medicação Contínua',
    search_professionals: 'Buscar Profissionais',
    nearby_clinics: 'Clínicas Próximas',
    user_recommendations: 'Recomendações dos Usuários',
    add_recommendation: 'Adicionar Indicação',
    legal_disclaimer: 'As informações exibidas nesta área são provenientes de fontes públicas disponíveis na internet e de recomendações compartilhadas por usuários. O MyPetCare não valida, certifica ou se responsabiliza pelos serviços prestados pelos profissionais listados.',
    my_veterinarian: 'Meu Veterinário',
    reports: 'Relatórios',
    symptom_guidance: 'Orientação de Sintomas',
    symptoms_placeholder: 'Descreva os sintomas (ex: vômito, falta de apetite)...',
    ai_guidance_warning: 'Esta orientação é baseada em IA e não substitui uma consulta veterinária. Não fornecemos diagnósticos definitivos.',
    possible_causes: 'Possíveis causas',
    urgency_level: 'Nível de urgência',
    recommendation: 'Recomendação',
    notifications: 'Notificações',
    push_notifications: 'Ativar Notificações Push',
    email_reminders: 'Ativar Lembretes por E-mail',
    vaccine_history: 'Histórico de Vacinas',
    medications_history: 'Histórico de Medicamentos',
    observations: 'Observações',
    attachments: 'Anexos',
    export_report: 'Exportar Relatório',
    share_whatsapp: 'Compartilhar WhatsApp',
    share_email: 'Compartilhar E-mail',
    name: 'Nome',
    phone: 'Telefone',
    address: 'Endereço',
    distance: 'Distância',
    open_maps: 'Abrir no Google Maps',
    call: 'Ligar',
    city: 'Cidade',
    state: 'Estado',
    rating: 'Avaliação',
    comment: 'Comentário',
    type: 'Tipo',
    veterinarian: 'Veterinário',
    clinic: 'Clínica',
    pet_shop: 'Pet Shop',
    add_event: 'Adicionar Evento',
    edit_event: 'Editar Evento',
    vaccine: 'Vacina',
    medication_event: 'Medicamento',
    appointment: 'Consulta',
    special_care: 'Cuidado Especial',
    age: 'Idade',
    years: 'anos',
    months: 'meses',
    welcome_message: 'Onde cada batida do coração é cuidada.',
    symptoms_description: 'Descreva os sintomas do seu pet para suporte preliminar por IA.',
    urgency_low: 'Baixa',
    urgency_medium: 'Média',
    urgency_high: 'Alta',
    urgency_emergency: 'Emergência',
    install_mypetcare: 'Instalar MyPetCare',
    app_settings: 'Configurações do App',
    account_settings: 'Conta',
    support_settings: 'Suporte',
    help_center: 'Central de Ajuda',
    sign_out: 'Sair',
    privacy_security: 'Privacidade e Segurança',
    pet_not_found: 'Pet não encontrado',
    no_events: 'Nenhum evento agendado ainda.',
    manage_routine: 'Gerencie a rotina e consultas médicas do seu pet.',
    trusted_network: 'Sua rede de confiança de profissionais pet.',
    delete_contact_confirm: 'Excluir este contato?',
    new_contact: 'Novo Contato',
    select_pet: 'Selecionar Pet',
    event_type: 'Tipo de Evento',
    event_title: 'Título',
    event_date: 'Data',
    event_time: 'Hora',
    event_recurrence: 'Recorrência',
    recurrence_none: 'Sem recorrência',
    recurrence_daily: 'Diária',
    recurrence_weekly: 'Semanal',
    recurrence_monthly: 'Mensal',
    recurrence_yearly: 'Anual',
    event_title_placeholder: 'ex: Vacina Anual',
    weight_trend: 'Tendência de Peso',
    last_6_months: 'Últimos 6 meses',
    no_pet_selected: 'Selecione um pet para ver os relatórios.',
    no_pets: 'Você ainda não adicionou nenhum pet.',
    tips_community: 'Dicas compartilhadas pela nossa comunidade de tutores.',
    health_report_for: 'Relatório de Saúde para',
    history_label: 'Histórico',
    no_info_registered: 'Nenhuma informação específica registrada.',
    manage_account_description: 'Gerencie sua conta e preferências.',
    choose_language: 'Escolha seu idioma',
    language_change_later: 'Você pode mudar isso depois nas configurações.',
    view_details: 'Ver detalhes',
    confirm_delete_pet: 'Tem certeza que deseja excluir este perfil de pet?',
    pet_name_placeholder: 'ex: Luna',
    breed_placeholder: 'ex: Golden Retriever',
    food_type_placeholder: 'ex: Ração Seca, Dieta Natural',
    allergies_placeholder: 'ex: Frango, Lactose',
    medical_notes_placeholder: 'Qualquer observação médica...',
    health_conditions_allergies: 'Condições de Saúde e Alergias',
    delete_pet: 'Excluir Pet',
    magic_link_title: 'Entrar no MyPetCare',
    magic_link_subtitle: 'Informe seu e-mail para receber o link de acesso.',
    magic_link_email_label: 'Endereço de E-mail',
    magic_link_send_button: 'Enviar Link de Acesso',
    magic_link_sent_title: 'Link enviado!',
    magic_link_sent_message: 'Verifique sua caixa de entrada. Clique no link para acessar sua conta.',
    magic_link_resend: 'Reenviar link',
    magic_link_note: 'Sem senha necessária. Acesso rápido e seguro.',
    location_permission: 'Permissão de localização necessária.',
    search_by_city: 'Buscar por cidade',
    city_placeholder: 'ex: São Paulo',
    search: 'Buscar',
    local_name: 'Nome do local',
    local_name_placeholder: 'ex: Clínica Vet Animal',
    add_review_title: 'Indicar Profissional',
    submit: 'Enviar',
    no_recommendations: 'Nenhuma indicação ainda. Seja o primeiro!',
    print_report: 'Imprimir Relatório',
    notes: 'Notas',
    loading_clinics: 'Buscando clínicas...',
    no_clinics_found: 'Nenhuma clínica encontrada nesta região.',
    error_fetching_clinics: 'Erro ao buscar clínicas. Tente novamente.',
    search_radius: 'Raio de busca',
    refresh_with_new_radius: 'Atualizar resultados com novo raio',
    back: 'Voltar',
    whatsapp: 'WhatsApp',
    weight_updated: 'Peso Atualizado',
    weight_changed_from: 'Peso alterado de',
    to: 'para',
    food_updated: 'Alimentação Atualizada',
    food_changed_from: 'Alimentação alterada de',
    significant_weight_change: 'Mudança significativa de peso detectada',
    is_data_correct: 'O preenchimento está correto',
    seek_trusted_vet: 'Recomendamos que você procure seu veterinário de confiança para avaliar esta mudança de peso.',
    pet_documents: 'Documentos do pet',
    attach_file: 'Anexar Arquivo',
    take_photo: 'Tirar Foto',
    no_attachments: 'Nenhum documento anexado.',
    compiled_history: 'Compilado Histórico',
    pet_age: 'Idade do Pet',
    current_weight: 'Peso Atual',
    last_update: 'Última Atualização',
    save_success: 'Salvo com sucesso!',
    download: 'Baixar',
    share: 'Compartilhar',
    confirm_delete_document: 'Tem certeza que deseja excluir este documento?',
    tutor_profile: 'Perfil do Tutor',
    subscription_plan: 'Plano de Assinatura',
    current_plan: 'Plano Atual',
    change_photo: 'Mudar Foto',
    active: 'Ativo',
    inactive: 'Inativo',
    register_whatsapp_first: 'Por favor, cadastre seu WhatsApp no perfil primeiro.',
    send_to_my_whatsapp: 'Enviar para meu WhatsApp',
    email_reminders_label: 'Lembretes por E-mail',
    password: 'Senha',
    login_with_password: 'Entrar com Senha',
    login_with_magic_link: 'Entrar com Link Mágico',
    dont_have_account: 'Não tem uma conta?',
    sign_up: 'Cadastrar-se',
    invalid_credentials: 'E-mail ou senha incorretos.',
    login_title: 'Entrar no MyPetCare',
    register_title: 'Criar Conta',
    direct_access: 'Acesso Direto (Bypass)',
    update_weight: 'Atualizar Peso',
    initial_weight: 'Peso Inicial',
    first_weight_registered: 'Primeiro peso registrado',
    no_weight_data: 'Sem registros de peso',
    recommend_to_community: 'Recomendar à Comunidade',
    share_with_tutors: 'Compartilhe este local com outros tutores',
  },
  en: {
    welcome_back: 'Welcome back',
    this_weeks_agenda: "This Week's Agenda",
    dashboard: 'Dashboard',
    agenda: 'Agenda',
    clinics: 'Clinics',
    profile: 'Profile',
    logout: 'Log Out',
    install_app: 'Install App',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    add_pet: 'Add Pet',
    edit_pet: 'Edit Pet',
    everything_up_to_date: 'Everything up to date',
    pending_care: '1 pending care',
    overdue_vaccines: 'Overdue vaccines',
    view_full_profile: 'View full profile',
    weight: 'Weight',
    birthday: 'Birthday',
    health_nutrition: 'Health & Nutrition',
    basic_identity: 'Basic Identity',
    pet_name: 'Pet Name',
    breed: 'Breed',
    birth_date: 'Birth Date',
    food_type: 'Food Type',
    allergies: 'Allergies',
    health_conditions: 'Health Conditions',
    medication: 'Continuous Medication',
    search_professionals: 'Search Professionals',
    nearby_clinics: 'Nearby Clinics',
    user_recommendations: 'User Recommendations',
    add_recommendation: 'Add Recommendation',
    legal_disclaimer: 'The information displayed in this area comes from public sources available on the internet and from recommendations shared by users. MyPetCare does not validate, certify or take responsibility for the services provided by the listed professionals.',
    my_veterinarian: 'My Veterinarian',
    reports: 'Reports',
    symptom_guidance: 'Symptom Guidance',
    symptoms_placeholder: 'Describe symptoms (e.g. vomiting, lack of appetite)...',
    ai_guidance_warning: 'This guidance is AI-based and does not replace a veterinary consultation. We do not provide definitive diagnoses.',
    possible_causes: 'Possible causes',
    urgency_level: 'Urgency level',
    recommendation: 'Recommendation',
    notifications: 'Notifications',
    push_notifications: 'Enable Push Notifications',
    email_reminders: 'Enable Email Reminders',
    vaccine_history: 'Vaccine History',
    medications_history: 'Medications History',
    observations: 'Observations',
    attachments: 'Attachments',
    export_report: 'Export Report',
    share_whatsapp: 'Share WhatsApp',
    share_email: 'Share Email',
    name: 'Name',
    phone: 'Phone',
    address: 'Address',
    distance: 'Distance',
    open_maps: 'Open in Google Maps',
    call: 'Call',
    city: 'City',
    state: 'State',
    rating: 'Rating',
    comment: 'Comment',
    type: 'Type',
    veterinarian: 'Veterinarian',
    clinic: 'Clinic',
    pet_shop: 'Pet Shop',
    add_event: 'Add Event',
    edit_event: 'Edit Event',
    vaccine: 'Vaccine',
    medication_event: 'Medication',
    appointment: 'Appointment',
    special_care: 'Special Care',
    age: 'Age',
    years: 'years',
    months: 'months',
    welcome_message: 'Where every heartbeat is nurtured.',
    symptoms_description: "Describe your pet's symptoms for preliminary AI support.",
    urgency_low: 'Low',
    urgency_medium: 'Medium',
    urgency_high: 'High',
    urgency_emergency: 'Emergency',
    install_mypetcare: 'Install MyPetCare',
    app_settings: 'App Settings',
    account_settings: 'Account',
    support_settings: 'Support',
    help_center: 'Help Center',
    sign_out: 'Sign Out',
    privacy_security: 'Privacy & Security',
    pet_not_found: 'Pet not found',
    no_events: 'No events scheduled yet.',
    manage_routine: "Manage your pet's routine and medical appointments.",
    trusted_network: 'Your trusted network of pet care professionals.',
    delete_contact_confirm: 'Delete this contact?',
    new_contact: 'New Contact',
    select_pet: 'Select Pet',
    event_type: 'Event Type',
    event_title: 'Title',
    event_date: 'Date',
    event_time: 'Time',
    event_recurrence: 'Recurrence',
    recurrence_none: 'No recurrence',
    recurrence_daily: 'Daily',
    recurrence_weekly: 'Weekly',
    recurrence_monthly: 'Monthly',
    recurrence_yearly: 'Yearly',
    event_title_placeholder: 'e.g. Annual Vaccine',
    weight_trend: 'Weight Trend',
    last_6_months: 'Last 6 months',
    no_pet_selected: 'Select a pet to view reports.',
    no_pets: "You haven't added any pets yet.",
    tips_community: 'Tips shared by our community of tutors.',
    health_report_for: 'Health Report for',
    history_label: 'History',
    no_info_registered: 'No specific information registered.',
    manage_account_description: 'Manage your account and preferences.',
    choose_language: 'Choose your language',
    language_change_later: 'You can change this later in settings.',
    view_details: 'View details',
    confirm_delete_pet: 'Are you sure you want to delete this pet profile?',
    pet_name_placeholder: 'e.g. Luna',
    breed_placeholder: 'e.g. Golden Retriever',
    food_type_placeholder: 'e.g. Dry Kibble, Raw Diet',
    allergies_placeholder: 'e.g. Chicken, Dairy',
    medical_notes_placeholder: 'Any medical notes...',
    health_conditions_allergies: 'Health Conditions & Allergies',
    delete_pet: 'Delete Pet',
    magic_link_title: 'Sign in to MyPetCare',
    magic_link_subtitle: 'Enter your email to receive your access link.',
    magic_link_email_label: 'Email Address',
    magic_link_send_button: 'Send Access Link',
    magic_link_sent_title: 'Link sent!',
    magic_link_sent_message: 'Check your inbox and click the link to access your account.',
    magic_link_resend: 'Resend link',
    magic_link_note: 'No password needed. Fast and secure access.',
    location_permission: 'Location permission required.',
    search_by_city: 'Search by city',
    city_placeholder: 'e.g. New York',
    search: 'Search',
    local_name: 'Place name',
    local_name_placeholder: 'e.g. Happy Paws Clinic',
    add_review_title: 'Recommend a Professional',
    submit: 'Submit',
    no_recommendations: 'No recommendations yet. Be the first!',
    print_report: 'Print Report',
    notes: 'Notes',
    loading_clinics: 'Searching for clinics...',
    no_clinics_found: 'No clinics found in this region.',
    error_fetching_clinics: 'Error searching for clinics. Try again.',
    search_radius: 'Search radius',
    refresh_with_new_radius: 'Update results with new radius',
    back: 'Back',
    whatsapp: 'WhatsApp',
    weight_updated: 'Weight Updated',
    weight_changed_from: 'Weight changed from',
    to: 'to',
    food_updated: 'Food Updated',
    food_changed_from: 'Food changed from',
    significant_weight_change: 'Significant weight change detected',
    is_data_correct: 'Is this information correct',
    seek_trusted_vet: 'We recommend that you seek your trusted veterinarian to evaluate this weight change.',
    pet_documents: 'Pet Documents',
    attach_file: 'Attach File',
    take_photo: 'Take Photo',
    no_attachments: 'No documents attached.',
    compiled_history: 'Compiled History',
    pet_age: 'Pet Age',
    current_weight: 'Current Weight',
    last_update: 'Last Update',
    save_success: 'Saved successfully!',
    download: 'Download',
    share: 'Share',
    confirm_delete_document: 'Are you sure you want to delete this document?',
    tutor_profile: 'Tutor Profile',
    subscription_plan: 'Subscription Plan',
    current_plan: 'Current Plan',
    change_photo: 'Change Photo',
    active: 'Active',
    inactive: 'Inactive',
    register_whatsapp_first: 'Please register your WhatsApp in your profile first.',
    send_to_my_whatsapp: 'Send to my WhatsApp',
    email_reminders_label: 'Email Reminders',
    password: 'Password',
    login_with_password: 'Login with Password',
    login_with_magic_link: 'Login with Magic Link',
    dont_have_account: "Don't have an account?",
    sign_up: 'Sign Up',
    invalid_credentials: 'Invalid email or password.',
    login_title: 'Login to MyPetCare',
    register_title: 'Create Account',
    direct_access: 'Direct Access (Bypass)',
    update_weight: 'Update Weight',
    initial_weight: 'Initial Weight',
    first_weight_registered: 'First weight registered',
    no_weight_data: 'No weight records',
    recommend_to_community: 'Recommend to Community',
    share_with_tutors: 'Share this place with other tutors',
  },
  es: {
    welcome_back: 'Bienvenido de nuevo',
    this_weeks_agenda: 'Agenda de la Semana',
    dashboard: 'Panel',
    agenda: 'Agenda',
    clinics: 'Clínicas',
    profile: 'Perfil',
    logout: 'Cerrar Sesión',
    install_app: 'Instalar App',
    save: 'Guardar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Eliminar',
    add_pet: 'Agregar Mascota',
    edit_pet: 'Editar Mascota',
    everything_up_to_date: 'Todo al día',
    pending_care: '1 cuidado pendiente',
    overdue_vaccines: 'Vacunas atrasadas',
    view_full_profile: 'Ver ficha completa',
    weight: 'Peso',
    birthday: 'Cumpleaños',
    health_nutrition: 'Salud y Nutrición',
    basic_identity: 'Identidad Básica',
    pet_name: 'Nombre de la Mascota',
    breed: 'Raza',
    birth_date: 'Fecha de Nacimiento',
    food_type: 'Alimentación',
    allergies: 'Alergias',
    health_conditions: 'Condiciones de Salud',
    medication: 'Medicación Continua',
    search_professionals: 'Buscar Profesionales',
    nearby_clinics: 'Clínicas Cercanas',
    user_recommendations: 'Recomendaciones de Usuarios',
    add_recommendation: 'Agregar Recomendación',
    legal_disclaimer: 'La información mostrada en esta área proviene de fuentes públicas disponibles en internet y de recomendaciones compartidas por los usuarios. MyPetCare no valida, certifica ni se responsabiliza por los servicios prestados por los profesionales listados.',
    my_veterinarian: 'Mi Veterinario',
    reports: 'Informes',
    symptom_guidance: 'Orientación de Síntomas',
    symptoms_placeholder: 'Describa los síntomas (ej: vómito, falta de apetito)...',
    ai_guidance_warning: 'Esta orientación se basa en IA y no reemplaza una consulta veterinaria. No proporcionamos diagnósticos definitivos.',
    possible_causes: 'Posibles causas',
    urgency_level: 'Nivel de urgencia',
    recommendation: 'Recomendación',
    notifications: 'Notificaciones',
    push_notifications: 'Activar Notificaciones Push',
    email_reminders: 'Activar Recordatorios por Email',
    vaccine_history: 'Historial de Vacunas',
    medications_history: 'Historial de Medicamentos',
    observations: 'Observaciones',
    attachments: 'Anexos',
    export_report: 'Exportar Informe',
    share_whatsapp: 'Compartir WhatsApp',
    share_email: 'Compartir Email',
    name: 'Nombre',
    phone: 'Teléfono',
    address: 'Dirección',
    distance: 'Distancia',
    open_maps: 'Abrir en Google Maps',
    call: 'Llamar',
    city: 'Ciudad',
    state: 'Estado',
    rating: 'Calificación',
    comment: 'Comentario',
    type: 'Tipo',
    veterinarian: 'Veterinario',
    clinic: 'Clínica',
    pet_shop: 'Pet Shop',
    add_event: 'Agregar Evento',
    edit_event: 'Editar Evento',
    vaccine: 'Vacuna',
    medication_event: 'Medicamento',
    appointment: 'Cita',
    special_care: 'Cuidado Especial',
    age: 'Edad',
    years: 'años',
    months: 'meses',
    welcome_message: 'Donde cada latido es cuidado.',
    symptoms_description: 'Describa los síntomas de su mascota para soporte preliminar por IA.',
    urgency_low: 'Baja',
    urgency_medium: 'Media',
    urgency_high: 'Alta',
    urgency_emergency: 'Emergencia',
    install_mypetcare: 'Instalar MyPetCare',
    app_settings: 'Configuración de la App',
    account_settings: 'Cuenta',
    support_settings: 'Soporte',
    help_center: 'Centro de Ayuda',
    sign_out: 'Cerrar Sesión',
    privacy_security: 'Privacidad y Seguridad',
    pet_not_found: 'Mascota no encontrada',
    no_events: 'No hay eventos programados aún.',
    manage_routine: 'Gestione la rutina y consultas médicas de su mascota.',
    trusted_network: 'Su red de confianza de profesionales para mascotas.',
    delete_contact_confirm: '¿Eliminar este contacto?',
    new_contact: 'Nuevo Contacto',
    select_pet: 'Seleccionar Mascota',
    event_type: 'Tipo de Evento',
    event_title: 'Título',
    event_date: 'Fecha',
    event_time: 'Hora',
    event_recurrence: 'Recurrencia',
    recurrence_none: 'Sin recurrencia',
    recurrence_daily: 'Diaria',
    recurrence_weekly: 'Semanal',
    recurrence_monthly: 'Mensual',
    recurrence_yearly: 'Anual',
    event_title_placeholder: 'ej: Vacuna Anual',
    weight_trend: 'Tendencia de Peso',
    last_6_months: 'Últimos 6 meses',
    no_pet_selected: 'Seleccione una mascota para ver los informes.',
    no_pets: 'Aún no has agregado ninguna mascota.',
    tips_community: 'Consejos compartidos por nuestra comunidad de tutores.',
    health_report_for: 'Informe de Salud para',
    history_label: 'Historial',
    no_info_registered: 'No hay información específica registrada.',
    manage_account_description: 'Gestione su cuenta y preferencias.',
    choose_language: 'Elige tu idioma',
    language_change_later: 'Puedes cambiarlo más tarde en la configuración.',
    view_details: 'Ver detalles',
    confirm_delete_pet: '¿Estás seguro de que quieres eliminar este perfil de mascota?',
    pet_name_placeholder: 'ej: Luna',
    breed_placeholder: 'ej: Golden Retriever',
    food_type_placeholder: 'ej: Comida Seca, Dieta Natural',
    allergies_placeholder: 'ej: Pollo, Lácteos',
    medical_notes_placeholder: 'Cualquier nota médica...',
    health_conditions_allergies: 'Condiciones de Salud y Alergias',
    delete_pet: 'Eliminar Mascota',
    magic_link_title: 'Iniciar sesión en MyPetCare',
    magic_link_subtitle: 'Ingrese su email para recibir su enlace de acceso.',
    magic_link_email_label: 'Dirección de Email',
    magic_link_send_button: 'Enviar Enlace de Acceso',
    magic_link_sent_title: '¡Enlace enviado!',
    magic_link_sent_message: 'Revise su bandeja de entrada y haga clic en el enlace para acceder.',
    magic_link_resend: 'Reenviar enlace',
    magic_link_note: 'Sin contraseña necesaria. Acceso rápido y seguro.',
    location_permission: 'Se requiere permiso de ubicación.',
    search_by_city: 'Buscar por ciudad',
    city_placeholder: 'ej: Buenos Aires',
    search: 'Buscar',
    local_name: 'Nombre del local',
    local_name_placeholder: 'ej: Clínica Vet Animal',
    add_review_title: 'Recomendar un Profesional',
    submit: 'Enviar',
    no_recommendations: 'Sin recomendaciones aún. ¡Sé el primero!',
    print_report: 'Imprimir Informe',
    notes: 'Notas',
    loading_clinics: 'Buscando clínicas...',
    no_clinics_found: 'No se encontraron clínicas nesta región.',
    error_fetching_clinics: 'Error al buscar clínicas. Inténtalo de nuevo.',
    search_radius: 'Radio de búsqueda',
    refresh_with_new_radius: 'Actualizar resultados con nuevo radio',
    back: 'Volver',
    whatsapp: 'WhatsApp',
    weight_updated: 'Peso Actualizado',
    weight_changed_from: 'Peso cambiado de',
    to: 'para',
    food_updated: 'Alimentación Actualizada',
    food_changed_from: 'Alimentación cambiada de',
    significant_weight_change: 'Se detectó um cambio significativo de peso',
    is_data_correct: '¿Es correcta esta información?',
    seek_trusted_vet: 'Le recomendamos que busque a su veterinario de confianza para evaluar este cambio de peso.',
    pet_documents: 'Documentos del pet',
    attach_file: 'Adjuntar Archivo',
    take_photo: 'Tomar Foto',
    no_attachments: 'Sin documentos adjuntos.',
    compiled_history: 'Historial Compilado',
    pet_age: 'Edad del Pet',
    current_weight: 'Peso Actual',
    last_update: 'Última Actualización',
    save_success: '¡Guardado con éxito!',
    download: 'Descargar',
    share: 'Compartir',
    confirm_delete_document: '¿Estás seguro de que quieres eliminar este documento?',
    tutor_profile: 'Perfil del Tutor',
    subscription_plan: 'Plan de Suscripción',
    current_plan: 'Plan Actual',
    change_photo: 'Cambiar Foto',
    active: 'Activo',
    inactive: 'Inactivo',
    register_whatsapp_first: 'Por favor, registre su WhatsApp en su perfil primero.',
    send_to_my_whatsapp: 'Enviar a mi WhatsApp',
    email_reminders_label: 'Recordatorios por Email',
    password: 'Contraseña',
    login_with_password: 'Iniciar sesión con contraseña',
    login_with_magic_link: 'Iniciar sesión con enlace mágico',
    dont_have_account: '¿No tienes una cuenta?',
    sign_up: 'Registrarse',
    invalid_credentials: 'Email o contraseña incorrectos.',
    login_title: 'Iniciar sesión en MyPetCare',
    register_title: 'Crear Cuenta',
    direct_access: 'Acceso Directo (Bypass)',
    update_weight: 'Actualizar Peso',
    initial_weight: 'Peso Inicial',
    first_weight_registered: 'Primer peso registrado',
    no_weight_data: 'Sin registros de peso',
    recommend_to_community: 'Recomendar a la Comunidad',
    share_with_tutors: 'Comparte este lugar con otros tutores',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language | null>(() => {
    const saved = localStorage.getItem('mypetcare_lang');
    return (saved as Language) || null;
  });

  const setLanguage = (lang: Language | null) => {
    setLanguageState(lang);
    if (lang) {
      localStorage.setItem('mypetcare_lang', lang);
    } else {
      localStorage.removeItem('mypetcare_lang');
    }
  };

  const t = (key: string): string => {
    if (!language) return key;
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
